spring.application.name=set-checklist
spring.datasource.url=jdbc:h2:mem:jhdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update